language: bash

# 发布所有镜像

services:
  - docker
env:
  global:
    - NAME="peng49/php"
#    - BRANCH="${TRAVIS_BRANCH}"
    - TAG="${TRAVIS_TAG/-*/}"
    - DOCKERFILE=Dockerfile
    - VERSION="v${TRAVIS_TAG/*-/}"

# https://docs.travis-ci.com/user/conditions-v1
#if: branch = pro OR branch = dev OR branch = ops OR tag IS present
#if: tag IS present AND tag =~ /^(dev|pro)/
if: branch = master

addons:
  apt:
    # The docker manifest command was added in docker-ee version 18.x
    # So update our current installation and we also have to enable the experimental features.
    sources:
      - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        key_url: "https://download.docker.com/linux/ubuntu/gpg"
    packages:
      - docker-ce

before_install:
  - docker --version
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

install:
  # entrypoint.sh 添加可执行权限
  - chmod +x entrypoint.sh

before_script:
  - docker build -t peng49/php:latest -f Dockerfile .
  - docker tag peng49/php:latest peng49/php:pro
  - docker build -t peng49/php:dev -f Dockerfile.dev .
  - docker build -t peng49/php:gocron -f Dockerfile.gocron .

script:
  - docker push peng49/php:latest
  - docker push peng49/php:pro
  - docker push peng49/php:dev
  - docker push peng49/php:gocron

before_deploy:
  - echo "prepare deploy"

deploy:
  provider: script
  on:
    all_branches: true
  script: bash -c 'echo "deploy"'
