name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag peng49/php:latest
        docker tag peng49/php:latest peng49/php:pro

    - name: Deploy image
      env:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASS}}
      run: |
        echo "${password}" | docker login -u "${username}" --password-stdin
        docker push peng49/php:latest
        docker push peng49/php:pro

  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile.dev --tag peng49/php:dev

      - name: Deploy image
        env:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}
        run: |
          echo "${password}" | docker login -u "${username}" --password-stdin
          docker push peng49/php:dev

  gocron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        env:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}
        run: |
          docker build . --file Dockerfile.gocron --tag peng49/php:gocron

      - name: Deploy image
        env:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}
        run: |
          echo "${password}" | docker login -u "${username}" --password-stdin
          docker push peng49/php:gocron

  swoole:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile.swoole --tag peng49/php:swoole

      - name: Deploy image
        env:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}
        run: |
          echo "${password}" | docker login -u "${username}" --password-stdin
          docker push peng49/php:swoole
